### ISSUE TITLE
disappearing checkboxes

### ISSUE THREAD

**Issue by ozgurkanb** [yikesinc/yikes-inc-easy-mailchimp-extender#348]
I've recently created a mailchimp form in my website. But the problem is chechboxes disapparing when mouseover. Users couldn't click on labels, since checkboxes disappear.

Here you can control: http://rahatbatti.com/

**Comment by EvanHerman** [comment]
Hi,

You have a style declaration in your CSS file (which is un-related to this plugin).

**jcss.php**
```css
textarea:hover, input:hover, textarea:active, input:active, textarea:focus, input:focus, button:focus, button:active, button:hover {
  -webkit-appearance: none;
}
```

When that is removed, the issue will be resolved.

Thanks,
Evan
