### ISSUE TITLE
Submit button different size

### ISSUE THREAD

**Issue by theliveman** [yikesinc/yikes-inc-easy-mailchimp-extender#478]
Hi there,
I'm trying to add the form in to a post but the submit button looks totally off. Kindly help.
The link in question [http://www.whimsicalchef.com/2016/03/23/seeni-sambol-caramelized-onion-relish/](url) scroll down to the page.

![submit button](https://cloud.githubusercontent.com/assets/18072114/14046218/d8f07fac-f2da-11e5-8692-ff686f29758c.png)

could you also please let me know how to change the submit button color and add a background color to the form to make it stand out?

**Comment by TheTracyL** [comment]
Hello.

This CSS code will get the button to line up:

```CSS
.yikes-easy-mc-form.yikes-easy-mc-form-1 span.empty-label {
	display: none;
}
```
You have a few options to add CSS code:
-     If you created this theme yourself, you can just add it to your style.css file
-     If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
-     Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
-     You can use a plugin like [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or Jetpack and enter the code in their Custom CSS area

The other items you could actually accomplish with our [customizer add-on](https://yikesplugins.com/plugin/form-customizer-for-easy-forms-for-mailchimp/) if you are interested.

Thank you!
-Tracy

**Comment by theliveman** [comment]
Hi Tracy,
It's not still lining up

**Comment by theliveman** [comment]
Sorry Tracy, it has aligned but the submit button size is bigger than the fields

**Comment by theliveman** [comment]
I tried using the following code advised in another solution but didn't work

.yikes-easy-mc-form .yikes-easy-mc-submit-button { min-height: 30px; padding: 6px 10px; }

**Comment by TheTracyL** [comment]
Hi there,

Try this:
```CSS
.yikes-easy-mc-form.yikes-easy-mc-form-1 .yikes-easy-mc-submit-button {
    min-height: 20px;
    padding: 5px 10px;
    font-size: 11px;
}
```
